globalProperties:
  apiTests: false
  modelTests: false
additionalProperties:
  moduleName: Buildium
  gemAuthor: LeadSimple
  gemAuthorEmail: engineering+buildium.gem@leadsimple.com
  gemHomepage: https://github.com/LeadSimple/buildium
  gemDescription: API client library for Buildium
  gemRequiredRubyVersion: "> 3.0.0"
  gemName: buildium-ruby
  gemVersion: 3.1.0
