=begin
#Open API, powered by Buildium

#GetAllGLAccounts) response message now includes the property `IsBankAccount`. This is a boolean property that indicates whether the general ledger account is also a bank account.  * A `Country` property has been added to all Address messages. This property contains an enumeration indicating the country of the address.     

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1

=end

require 'date'
require 'time'

module Buildium
  class AccountingSettingsMessage
    # The accounting book entity unique identifier.
    attr_accessor :accounting_book_id

    # The default bank account unique identifier.
    attr_accessor :default_bank_account_id

    # The default accounting basis.
    attr_accessor :default_accounting_basis

    # Indicates the type of trust account warnings are enable within the account, if any.
    attr_accessor :trust_account_warning

    # The month the fiscal year ends.
    attr_accessor :fiscal_year_end_month

    # The day the fiscal year ends.
    attr_accessor :fiscal_year_end_day

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'accounting_book_id' => :'AccountingBookId',
        :'default_bank_account_id' => :'DefaultBankAccountId',
        :'default_accounting_basis' => :'DefaultAccountingBasis',
        :'trust_account_warning' => :'TrustAccountWarning',
        :'fiscal_year_end_month' => :'FiscalYearEndMonth',
        :'fiscal_year_end_day' => :'FiscalYearEndDay'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'accounting_book_id' => :'Integer',
        :'default_bank_account_id' => :'Integer',
        :'default_accounting_basis' => :'String',
        :'trust_account_warning' => :'String',
        :'fiscal_year_end_month' => :'Integer',
        :'fiscal_year_end_day' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Buildium::AccountingSettingsMessage` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Buildium::AccountingSettingsMessage`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'accounting_book_id')
        self.accounting_book_id = attributes[:'accounting_book_id']
      end

      if attributes.key?(:'default_bank_account_id')
        self.default_bank_account_id = attributes[:'default_bank_account_id']
      end

      if attributes.key?(:'default_accounting_basis')
        self.default_accounting_basis = attributes[:'default_accounting_basis']
      end

      if attributes.key?(:'trust_account_warning')
        self.trust_account_warning = attributes[:'trust_account_warning']
      end

      if attributes.key?(:'fiscal_year_end_month')
        self.fiscal_year_end_month = attributes[:'fiscal_year_end_month']
      end

      if attributes.key?(:'fiscal_year_end_day')
        self.fiscal_year_end_day = attributes[:'fiscal_year_end_day']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      default_accounting_basis_validator = EnumAttributeValidator.new('String', ["Accrual", "Cash"])
      return false unless default_accounting_basis_validator.valid?(@default_accounting_basis)
      trust_account_warning_validator = EnumAttributeValidator.new('String', ["Off", "ByProperty", "ByRentalOwner"])
      return false unless trust_account_warning_validator.valid?(@trust_account_warning)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] default_accounting_basis Object to be assigned
    def default_accounting_basis=(default_accounting_basis)
      validator = EnumAttributeValidator.new('String', ["Accrual", "Cash"])
      unless validator.valid?(default_accounting_basis)
        fail ArgumentError, "invalid value for \"default_accounting_basis\", must be one of #{validator.allowable_values}."
      end
      @default_accounting_basis = default_accounting_basis
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] trust_account_warning Object to be assigned
    def trust_account_warning=(trust_account_warning)
      validator = EnumAttributeValidator.new('String', ["Off", "ByProperty", "ByRentalOwner"])
      unless validator.valid?(trust_account_warning)
        fail ArgumentError, "invalid value for \"trust_account_warning\", must be one of #{validator.allowable_values}."
      end
      @trust_account_warning = trust_account_warning
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          accounting_book_id == o.accounting_book_id &&
          default_bank_account_id == o.default_bank_account_id &&
          default_accounting_basis == o.default_accounting_basis &&
          trust_account_warning == o.trust_account_warning &&
          fiscal_year_end_month == o.fiscal_year_end_month &&
          fiscal_year_end_day == o.fiscal_year_end_day
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [accounting_book_id, default_bank_account_id, default_accounting_basis, trust_account_warning, fiscal_year_end_month, fiscal_year_end_day].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Buildium.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
