=begin
#Open API, powered by Buildium

#GetAllGLAccounts) response message now includes the property `IsBankAccount`. This is a boolean property that indicates whether the general ledger account is also a bank account.  * A `Country` property has been added to all Address messages. This property contains an enumeration indicating the country of the address.     

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Buildium::ClientLeadCreditRequestMessage
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Buildium::ClientLeadCreditRequestMessage do
  let(:instance) { Buildium::ClientLeadCreditRequestMessage.new }

  describe 'test an instance of ClientLeadCreditRequestMessage' do
    it 'should create an instance of ClientLeadCreditRequestMessage' do
      expect(instance).to be_instance_of(Buildium::ClientLeadCreditRequestMessage)
    end
  end
  describe 'test attribute "credit_status"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["Approved", "Declined", "Requested"])
      # validator.allowable_values.each do |value|
      #   expect { instance.credit_status = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "credit_reason"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["AccidentalFormSubmission", "DuplicateLead", "InvalidContactInformation", "JobSeeker", "Tenant", "Vendor", "WrongPropertyType", "WrongZipCode", "Other"])
      # validator.allowable_values.each do |value|
      #   expect { instance.credit_reason = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "comments"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "request_date"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
