=begin
#Open API, powered by Buildium

#GetAllGLAccounts) response message now includes the property `IsBankAccount`. This is a boolean property that indicates whether the general ledger account is also a bank account.  * A `Country` property has been added to all Address messages. This property contains an enumeration indicating the country of the address.   

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

require 'date'
require 'time'

module Buildium
  class ApplicationResponseFieldMessage
    # Indicates the field category type the field is assigned. The `FieldCategoryType` can be used to identify specific data points within the application. For example, to identify the fields that contain the applicants full name you would filter the fields within the application where the `FieldCategoryType` is equal to `ApplicantName`.
    attr_accessor :field_category_type

    # Indicates the fields expected input value format and/or data type. For example, a field can be assigned a `FieldType` of `DateDayMonthYear` which indicates the input value must be a date containing a day, month and year.
    attr_accessor :field_type

    # A user defined description of the field. This value is typically displayed as the form field label on the application.
    attr_accessor :field_label

    # The field input value from the applicant.
    attr_accessor :value

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'field_category_type' => :'FieldCategoryType',
        :'field_type' => :'FieldType',
        :'field_label' => :'FieldLabel',
        :'value' => :'Value'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'field_category_type' => :'String',
        :'field_type' => :'String',
        :'field_label' => :'String',
        :'value' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Buildium::ApplicationResponseFieldMessage` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Buildium::ApplicationResponseFieldMessage`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'field_category_type')
        self.field_category_type = attributes[:'field_category_type']
      end

      if attributes.key?(:'field_type')
        self.field_type = attributes[:'field_type']
      end

      if attributes.key?(:'field_label')
        self.field_label = attributes[:'field_label']
      end

      if attributes.key?(:'value')
        self.value = attributes[:'value']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      field_category_type_validator = EnumAttributeValidator.new('String', ["ApplicantName", "ApplicantEmail", "ApplicantSocialSecurityNumber", "ApplicantAlternateEmail", "ApplicantHomePhone", "ApplicantCellPhone", "ApplicantWorkPhone", "ApplicantFax", "ApplicantBirthDate", "ApplicantDriversLicense", "ApplicantCurrentAddress", "ApplicantAlternateAddress", "EmergencyContactName", "EmergencyContactRelationship", "EmergencyContactEmail", "EmergencyContactPhone", "OccupantName", "OccupantRelationship", "OccupantBirthDate", "OccupantEmail", "OccupantPhoneNumber", "CosignerName", "CosignerRelationship", "CosignerSocialSecurityNumber", "CosignerPhoneNumber", "CosignerEmail", "EmployerName", "EmployerAddress", "EmployerPhoneNumber", "EmployerEmail", "PositionHeld", "EmploymentDates", "MonthlyGrossSalary", "SupervisorName", "SupervisorTitle", "PetType", "PetName", "PetAge", "PetSpayedOrNeutered", "PetLicenseNumber", "PetWeight", "DesiredMoveInDate", "DesiredLeaseDuration", "DesiredRent", "DesiredNumberOfBedrooms", "DesiredNumberOfBathrooms", "ReferenceName", "ReferenceRelationship", "ReferencePhoneNumber", "ReferenceEmail", "RentalAddress", "RentalDates", "MonthlyRent", "ReasonForLeaving", "LandlordName", "LandlordPhoneNumber", "LandlordEmail", "VehicleMake", "VehicleModel", "VehicleColor", "VehicleYear", "VehicleLicensePlate", "AgreedTo", "AgreedBy", "CosignerAddress", "ApplicantAddress", "OtherComments", "EmailApplication"])
      return false unless field_category_type_validator.valid?(@field_category_type)
      field_type_validator = EnumAttributeValidator.new('String', ["TextSingleLine", "Email", "DateDayMonthYear", "Number", "DateMonthYear", "DateYear", "GroupHeading", "NumberOfBathrooms", "NumberOfBedrooms", "PhoneNumber", "SocialSecurityNumber", "TextMultipleLines", "TrueFalse", "YesNo", "Currency", "FirstName", "LastName", "DateRangeFromDate", "DateRangeToDate", "AddressCountry", "AddressStreet", "AddressCity", "AddressState", "AddressZip", "DriversLicenseNumber", "DriversLicenseState", "Attachment"])
      return false unless field_type_validator.valid?(@field_type)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] field_category_type Object to be assigned
    def field_category_type=(field_category_type)
      validator = EnumAttributeValidator.new('String', ["ApplicantName", "ApplicantEmail", "ApplicantSocialSecurityNumber", "ApplicantAlternateEmail", "ApplicantHomePhone", "ApplicantCellPhone", "ApplicantWorkPhone", "ApplicantFax", "ApplicantBirthDate", "ApplicantDriversLicense", "ApplicantCurrentAddress", "ApplicantAlternateAddress", "EmergencyContactName", "EmergencyContactRelationship", "EmergencyContactEmail", "EmergencyContactPhone", "OccupantName", "OccupantRelationship", "OccupantBirthDate", "OccupantEmail", "OccupantPhoneNumber", "CosignerName", "CosignerRelationship", "CosignerSocialSecurityNumber", "CosignerPhoneNumber", "CosignerEmail", "EmployerName", "EmployerAddress", "EmployerPhoneNumber", "EmployerEmail", "PositionHeld", "EmploymentDates", "MonthlyGrossSalary", "SupervisorName", "SupervisorTitle", "PetType", "PetName", "PetAge", "PetSpayedOrNeutered", "PetLicenseNumber", "PetWeight", "DesiredMoveInDate", "DesiredLeaseDuration", "DesiredRent", "DesiredNumberOfBedrooms", "DesiredNumberOfBathrooms", "ReferenceName", "ReferenceRelationship", "ReferencePhoneNumber", "ReferenceEmail", "RentalAddress", "RentalDates", "MonthlyRent", "ReasonForLeaving", "LandlordName", "LandlordPhoneNumber", "LandlordEmail", "VehicleMake", "VehicleModel", "VehicleColor", "VehicleYear", "VehicleLicensePlate", "AgreedTo", "AgreedBy", "CosignerAddress", "ApplicantAddress", "OtherComments", "EmailApplication"])
      unless validator.valid?(field_category_type)
        fail ArgumentError, "invalid value #{ field_category_type.inspect } for \"field_category_type\", must be one of #{validator.allowable_values}."
      end
      @field_category_type = field_category_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] field_type Object to be assigned
    def field_type=(field_type)
      validator = EnumAttributeValidator.new('String', ["TextSingleLine", "Email", "DateDayMonthYear", "Number", "DateMonthYear", "DateYear", "GroupHeading", "NumberOfBathrooms", "NumberOfBedrooms", "PhoneNumber", "SocialSecurityNumber", "TextMultipleLines", "TrueFalse", "YesNo", "Currency", "FirstName", "LastName", "DateRangeFromDate", "DateRangeToDate", "AddressCountry", "AddressStreet", "AddressCity", "AddressState", "AddressZip", "DriversLicenseNumber", "DriversLicenseState", "Attachment"])
      unless validator.valid?(field_type)
        fail ArgumentError, "invalid value #{ field_type.inspect } for \"field_type\", must be one of #{validator.allowable_values}."
      end
      @field_type = field_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          field_category_type == o.field_category_type &&
          field_type == o.field_type &&
          field_label == o.field_label &&
          value == o.value
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [field_category_type, field_type, field_label, value].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Buildium.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
